services:
  client:
    image: zenoshubh/fitflexity-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile # Should be your production Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: fitflexity-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - fitflexity
    depends_on:
      - server

  # SERVER (BUN BACKEND)
  # Exposes its port directly.
  server:
    image: zenoshubh/fitflexity-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile # Should be your production Dockerfile
    container_name: fitflexity-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: ./.env.server
    networks:
      - fitflexity
    depends_on:
      - postgres
      - valkey
      - qdrant

  migrator:
    image: zenoshubh/fitflexity-migrator:latest
    build:
      context: ./server # Backend ke Dockerfile ko use karega
      dockerfile: Dockerfile.migrator
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - fitflexity
    restart: "no"

  worker:
    image: zenoshubh/fitflexity-worker:latest
    build:
      context: ./worker
      dockerfile: Dockerfile 
    container_name: fitflexity-worker
    restart: unless-stopped
    env_file: ./.env.worker
    networks:
      - fitflexity

  postgres:
    container_name: fitflexity-db
    image: postgres:17.5-alpine3.22
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fitflexity
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - fitflexity
    depends_on:
      - postgres

  valkey:
    image: valkey/valkey:8.1.3-alpine3.22
    container_name: fitflexity-valkey
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    networks:
      - fitflexity

  qdrant:
    image: qdrant/qdrant:latest
    container_name: fitflexity-qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - fitflexity

networks:
  fitflexity:
    driver: bridge

volumes:
  postgres_data:
  valkey_data:
  qdrant_data:
