# Migrator Stage
FROM oven/bun:1.2.19

WORKDIR /server

COPY migrator.package.json ./package.json

RUN bun install

COPY /src/db/schemas ./src/db/schemas
COPY drizzle.config.ts ./

CMD ["bunx", "drizzle-kit", "push", "--config=drizzle.config.ts"]
