# .github/workflows/deploy.yml

name: Build, Push, and Deploy

on:
  push:
    branches: ["main"]

jobs:
  # JOB 1: Build and Push Docker Images
  build_and_push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Create environment files from secrets
        run: |
          echo "${{ secrets.DOT_ENV_MAIN }}" > .env
          echo "${{ secrets.DOT_ENV_SERVER }}" > .env.server
          echo "${{ secrets.DOT_ENV_WORKER }}" > .env.worker

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build all defined images
        run: docker compose build

      - name: Push all tagged images
        run: docker compose push

  # JOB 2: Deploy to VPS
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/shubh/fitflexity
            echo "${{ secrets.DOT_ENV_SERVER }}" > .env.server
            echo "${{ secrets.DOT_ENV_MAIN }}" > .env
            echo "${{ secrets.DOT_ENV_WORKER }}" > .env.worker

            git pull

            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

            docker compose pull

            docker compose up -d migrator

            docker wait $(docker compose ps -q migrator)

            docker compose up -d --force-recreate --no-build

            docker image prune -f
